### ISSUE TITLE
Player-Specific Options

### ISSUE THREAD

**Issue by Entrox-Licher** [argonui/SCED#247]
It would be really cool if we could make some of the options specific to individual players (particularly the playermat options), so each individual player can have things tailored to their own preferences.  Additionally it should also be possible to make the opening/closing of the menus be player specific as well.

**Comment by Chr1Z93** [comment]
This would certainly be possible, but could open a can of worms. Supporting this would lead to quite some edge cases that need special handling. I can see the use of this, but I'm not sold it's worth the effort (and cost of maintenance).

**Comment by Buhallin** [comment]
Assuming you've got a table-wide default with per-player options on top of that, it's pretty tricky to get right both in terms of logic and UI presentation.  Especially with the complexity and limitations of XMLUI, it's not something I think we could do with enough quality to be worth the cost.

**Comment by Chr1Z93** [comment]
As discussed, this is not on the roadmap
