### ISSUE TITLE
"Take a clue" hotkey: handle stacks of clues on a card

### ISSUE THREAD

**Issue by Chr1Z93** [argonui/SCED#290]
Right now it just looks for the first object with the correct memo and rotation. This can lead to "taking" a stack of clues.
(Note: normally there won't be stacks of clues on cards, but you never know...)

**Comment by Buhallin** [comment]
I believe that high clue count locations can result in stacks on initial flip.  Locations which replenish clues are also pretty likely to have a user spawn them into stacks.
