### ISSUE TITLE
Feature Request: Discard hotkey

### ISSUE THREAD

**Issue by Chr1Z93** [argonui/SCED#414]
Just like the discard buttons on the playermats, this would move a card to the respective discard pile and move objects on it to the trashcan

**Comment by Glitchy-Tozier** [comment]
If possible, it should also work on cards outside the playmats (e.g. on unengaged enemies, treacheries attached to locations or commited cards placed in front of other players' playmats).

**Comment by Entrox-Licher** [comment]
This should mostly be possible, but on the note of skill cards on other playmats: there is no way to track which deck a card came from. You _can_ track who pressed the discard hotkey, and send the card to their discard pile though. But worth noting the difference

**Comment by Chr1Z93** [comment]
I'm thinking that this should be the most convenient way:
- object is on playmat: trigger it for that playmat
- object is not on playmat: trigger it for the playmat of the player that pressed the hotkey

**Comment by Entrox-Licher** [comment]
Well for what it's worth that _also_ doesn't work for the commiting cards to other players scenario

**Comment by Glitchy-Tozier** [comment]
I like @Chr1Z93's proposal. Seems the most intuitive.
For the record: In my playgroups, we place commited cads in front of (instead of _on_) other player's playmats.
