### ISSUE TITLE
Investigator Minicards Inconsistent Usage of GMNotes

### ISSUE THREAD

**Issue by Entrox-Licher** [argonui/SCED#416]
Some of the minicards have their GMNotes stored within their respective JSON, some of them have them stored externally in a .gmnotes file.  We should pick one of the two methods and normalize it across all of them.

**Comment by Chr1Z93** [comment]
Further investigation led me to the discovery that the Mod Manager does not apply the char limit (I think it's about 100?) to these (probably because of the states?) and instead separates them into a separate file regardless of length.

**Comment by Chr1Z93** [comment]
Argonui confirmed that this is intended behaviour by the TTS Mod Manager, so this is out of our control for the moment.
