### ISSUE TITLE
Feature Request: Discard tokens from cards entering hand / leaving play

### ISSUE THREAD

**Issue by dscarpac** [argonui/SCED#422]
Example: Card with damage token on it returns to hand via Calling in Favors or Protecting the Anirniq, all tokens fall onto the table below the hand.

Could be fixed by sending tokens that fall onto this space to the trash (much like what happens with the discard pile).

**Comment by Entrox-Licher** [comment]
Worthwhile idea, but not as easy as it seems to implement.  There's no great way (that I can think of) to track the tokens that fall beneath the hand, without adding a lot of needless complexity.

Will require some more thought to see if something clicks

**Comment by dscarpac** [comment]
In the meantime I've just made a giant copy of the Token Remover and placed it underneath the hand, and that does work, although sending tokens to the Trash is more user friendly IMO.

**Comment by Entrox-Licher** [comment]
The main issue with this is that @Chr1Z93 has been working on a feature to dynamically move playmats, and adding another layer of complexity to that I think would be undesirable

**Comment by Chr1Z93** [comment]
I think we could just use handzones for this detection. If they are properly sized, tokens should never enter the hand zone on accident. So then we can just move entering objects (that are tokens) into the player's trash.
