### ISSUE TITLE
Better Handling of StartsInPlay & Permanent Importing

### ISSUE THREAD

**Issue by Entrox-Licher** [argonui/SCED#433]
In addition to adding the `StartsInPlay` tag to more objects that need it, we should add some support for splaying or spreading out the permanent & startsInPlay cards so that they can be better detected for scripting purposes (like Forced Learning) and just generally easier to detect.

**Comment by Chr1Z93** [comment]
`startsInPlay` should put cards directly in the playmat (we do have multiple "unnamed" slots that can be used for this). We should not do the same for all permanent cards though. So I'd apply this on a case-by-case basis for cards that you actually have an ability on them (like the Covenants for example). Something like Charisma / Relic Hunter can stay in a pile with the other `permanent` cards imo.

**Comment by Entrox-Licher** [comment]
100% agree!  This is in fact what I meant to say from the start, thank you for clarifying!

**Comment by Entrox-Licher** [comment]
An additional consideration here:  we might want to consider splaying out the permanents (similar to the customizable upgrades, with some overlap) in order to be able to properly detect cards that have special handling like Forced Learning @Chr1Z93
