### ISSUE TITLE
EotE: Add CleanupHelper_Ignore tag to Tekelili and Partners

### ISSUE THREAD

**Issue by Glitchy-Tozier** [argonui/SCED#444]
Those two piles get removed by the cleanup-helper.
![](https://media.discordapp.net/attachments/707791702512894054/1163153039679565824/image.png)

**Comment by Glitchy-Tozier** [comment]
It would also be helpful to not only add the tag to the deck, but also to all these individual cards (if that's not a thing in TTS and I'm making up functionality: ignore this comment).

**Comment by Chr1Z93** [comment]
Adding the tag to the decks will work, but cards in decks are not checked - so if you still have a Tekelili in your deck you'll still need to track that manually-

**Comment by Chr1Z93** [comment]
Added the tags to the decks for now and working on a separate tool to pull the tekeli-li cards from player decks / hands

**Comment by Glitchy-Tozier** [comment]
Sounds pretty neat!
