### ISSUE TITLE
Feature Request: Clue Helper

### ISSUE THREAD

**Issue by dscarpac** [argonui/SCED#461]
Two version of the same idea:

1) Now that we have a really awesome "take clue" hotkey, maybe we should have a "drop clue" hotkey (take one of your clues and put it at the location of the cursor), and a "spend clue" hotkey (move one of your clues to the trash). While the "spend all clues" button under the Act is excellent, often you don't want to spend all of your clues, and deciding who gets to keep how many involves dragging some number of clues from each person's clues away from that area, and then clicking the button. Spending one at a time with a hotkey would be a big improvement, IMO, and would also alleviate any difficulty separating clues that have stacked up.

2) However, even though using the hotkeys has been a real gamechanger for me in ease of us of the mod, I am slightly concerned that we'll have _too many_ hotkeys at some point. Another tactic here could be to introduce a clue helper, much like the handsize or search assistants. There can be one for each playmat, which would be very, very useful for two-handed solo without having to switch colors or cameras.
Mockup: 
![image](https://github.com/argonui/SCED/assets/148364064/9e798c4d-e32a-4ef2-ab3b-bc009ea98d16)

Intended behavior: 
take: "take one clue from location nearest to playermat's minicard"
drop: "move one clue from playermat's clues to location nearest to playermat's minicard"
spend: "move one clue from playermat's clues to nearest trashcan"
number: "modify 'one' in above to number listed. Resets to 'one' after one of above commands is clicked"

What do you think? Are these possible to create? Are both reasonable, or just one? The updates to the mod in the last year have been absolutely incredible so far!

**Comment by Chr1Z93** [comment]
Possible? Yes
Reasonable? Hm, not sure. "Take clue" is useful since you can accidentally pick up the locations. This is not an issue with spending.
Helper instead? I like that more than 2 more hotkeys, but am not sold on it yet 😅

**Comment by dscarpac** [comment]
To some extent the "spend clues" part is the most important to me -- breaking up a stack of 10 clues and spending 3 or 4 is cumbersome in my mind in TTS. Yes, you can right click and split the stack, or hold it and alt-right click, but to me these aren't really friendly solutions for something as ubiquitous as clue spending.

It's possible another solution to that issue is to make the discard hotkey only discard one item in a stack. Or maybe this could be part of the discard one "use" hotkey discussed on the Discord earlier.

**Comment by Chr1Z93** [comment]
> To some extent the "spend clues" part is the most important to me -- breaking up a stack of 10 clues and spending 3 or 4 is cumbersome in my mind in TTS. Yes, you can right click and split the stack, or hold it and alt-right click, but to me these aren't really friendly solutions for something as ubiquitous as clue spending.
> 
> It's possible another solution to that issue is to make the discard hotkey only discard one item in a stack. Or maybe this could be part of the discard one "use" hotkey discussed on the Discord earlier.

Oh that's a good idea! The "Remove one use" hotkey should allow you to just spend a clue of hovering a stack.
