### ISSUE TITLE
Improvement: Expand support for automatic setting of extra action token 

### ISSUE THREAD

**Issue by Entrox-Licher** [argonui/SCED#497]
In addition to there being more cases where the special action token could be automatically set (such as for once per round abilities), I wonder if it doesn't also make sense to change the data burden to be on the investigator cards instead of the playmats?

(Currently this functionality lives here:)
https://github.com/argonui/SCED/blob/10cc3d2fe84d81736c9e33a09695c006009ec9ef/src/playermat/Playmat.ttslua#L793-L807

**Comment by Chr1Z93** [comment]
Handled with https://github.com/argonui/SCED/pull/703
