### ISSUE TITLE
AllCardsBag Efficiency Improvements

### ISSUE THREAD

**Issue by Entrox-Licher** [argonui/SCED#552]
There are several things that could be done to improve the efficiency of the AllCardsBag script, especially in regards to loading hotfix bags.  A deep dive improvement of that script will be very useful.

- Make it so entire index doesn't get rebuilt when Hotfix Bags are adding to the index
- Make central functions into coroutines to better distribute load and lead to less stuttering of the mod on load

Please feel free to comment with more suggestions

**Comment by Chr1Z93** [comment]
Do you think it would be better to optimize this now or after the deckbuilder?

**Comment by Entrox-Licher** [comment]
After!  To avoid a truckload of merge conflicts haha
