### ISSUE TITLE
Fix / Enhancement to Explore Helper

### ISSUE THREAD

**Issue by dscarpac** [argonui/SCED#656]
Four issues have come up since we've published the explore helper:

1) Between Worlds erroneously is counted as a "location" for the location counter. This should be hard-coded as an exception to the usual code looking for the card metadata.
2) Users have requested that the "Draw" or "Discard" buttons that pop up after a treachery or enemy appears should reshuffle the locations below it back into the exploration deck.
3) "Draw" button should be added for story assets in Relics of the Past
4) Might be helpful to add a green border to locations that connect to the visible location that is revealed in the explore helper to help detect if the exploration is successful. (Perhaps a red border to all others). However, The Boundary Beyond does not work this way, so different logic could be used if this scenario is detected.

**Comment by Chr1Z93** [comment]
Sounds good to me!
Do you want to work on this?

**Comment by Chr1Z93** [comment]
Apparently, the "Return to" rules option isn't properly saved / loaded (https://discord.com/channels/704806269923491941/883448214471196732/1242412594904563762)

**Comment by dscarpac** [comment]
I'll add it to the pile of things :-D

**Comment by Chr1Z93** [comment]
I'll close this in favor of a new issue on the SCED-downloads repo because that's where the script lives.
