### ISSUE TITLE
Fix: Token spawning / removal

### ISSUE THREAD

**Issue by dscarpac** [argonui/SCED#769]
A number of related bugs/enhancements:
(1) Add token "rearrangement" to clue spawning for locations (Numpad 8) and potentially doom (Numpad 7) for player cards that do not have uses (e.g. David Renfield)
(2) Numpad 9 creates a stack of resource tokens on cards with uses that are unusual, like Old Keyring and Ravenous Myconid
(3) Remove One Use game key gives errors when card has no tokens on it and when card has the clickable resource counter
(4) When clickable resource tokens are disabled, Remove One Use game key could remove clickable counter when decreasing from 13 to 12 uses and spawn 12 tokens. (e.g. to make the reverse of Numpad 9)

**Comment by Chr1Z93** [comment]
I think I fixed pretty much all of that over here: https://github.com/argonui/SCED/pull/781

I personally don't like (4). If someone manually spawns a clickable counter, that should persist and not get removed
