### ISSUE TITLE
Update / Test / Combine Upkeep hotkeys

### ISSUE THREAD

**Issue by Chr1Z93** [argonui/SCED#969]

**Comment by YumiWhellie** [comment]
with a first read, I imagine this would be combining the hotkeys to one that would upkeep your own mat, but also upkeep any mat that has cards on it but no player seated. Is this it? If not, can you elaborate?

**Comment by Chr1Z93** [comment]
> with a first read, I imagine this would be combining the hotkeys to one that would upkeep your own mat, but also upkeep any mat that has cards on it but no player seated. Is this it? If not, can you elaborate?

Yeah, you got it
